import = [
    "~/.config/alacritty/themes/themes/nord.toml"
    # "~/.config/alacritty/themes/themes/nord_light.toml"
]

[font]
size = 14.0

[font.normal]
family = "Mononoki Nerd Font Mono" # https://madmalik.github.io/mononoki/
style = "Regular"

[window]
opacity = 1.0
