import = [
    # "~/.config/alacritty/themes/themes/nord.toml"
    "~/.config/alacritty/themes/themes/nord_light.toml"
]

[font]
size = 13.0

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[window]
opacity = 1.0
