import = [
  # NORD
  # "~/.config/alacritty/themes/themes/nord.toml"
  # "~/.config/alacritty/themes/themes/nord_light.toml"

  # CATPPUCCIN
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/themes/catppuccin.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 14.0

[font.normal]
family = "Mononoki Nerd Font Mono" # https://madmalik.github.io/mononoki/
style = "Regular"

[window]
opacity = 1.0

[env]
TERM = "xterm-256color"
