[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 13.0

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[schemes.nord.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[schemes.nord.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.nord.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[schemes.nord.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[schemes.nord.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[schemes.nord.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[schemes.nord.selection]
background = "#4c566a"
text = "CellForeground"

[schemes.nord.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.one_dark.cursor]
cursor = "#528bff"
text = "CellBackground"

[schemes.one_dark.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[schemes.one_dark.primary]
background = "#282c34"
foreground = "#abb2bf"

[schemes.one_dark.selection]
background = "#3e4451"
text = "CellForeground"

[schemes.one_light.cursor]
cursor = "#526eff"
text = "CellBackground"

[schemes.one_light.normal]
black = "#696c77"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#e45649"
white = "#a0a1a7"
yellow = "#c18401"

[schemes.one_light.primary]
background = "#fafafa"
foreground = "#383a42"

[schemes.one_light.selection]
background = "#e5e5e6"
text = "CellForeground"

[schemes.solarized_dark.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized_dark.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.solarized_dark.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized_dark.primary]
background = "#002b36"
foreground = "#839496"

[schemes.solarized_light.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized_light.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[schemes.solarized_light.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized_light.primary]
background = "#fdf6e3"
foreground = "#657b83"

[schemes.tomorrow_bright.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#2a2a2a"
yellow = "#e7c547"

[schemes.tomorrow_bright.normal]
black = "#000000"
blue = "#7aa6da"
cyan = "#70c0ba"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#424242"
yellow = "#e6c547"

[schemes.tomorrow_bright.primary]
background = "#000000"
foreground = "#eaeaea"

[schemes.tomorrow_dark.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#282a2e"
yellow = "#f0c674"

[schemes.tomorrow_dark.cursor]
cursor = "#ffffff"
text = "#1d1f21"

[schemes.tomorrow_dark.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[schemes.tomorrow_dark.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[window]
opacity = 1.0
