#!/usr/bin/env zsh

# Open this file to edit anytime
alias _alias="$EDITOR $0:A" # $0:A is ref to current script in ZSH

##
## General
##

# Go to ./dotfiles
alias dotfiles="cd $DOTFILES_DIR"

# Allow aliases to be with sudo
alias sudo="sudo "

# Easily refresh the shell by sourcing .zsh
alias refresh="source ~/.zshrc"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# ZSH / Oh My ZSH
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"

# Show system info using gotop
alias sysinfo="gotop"


##
## File System
##

# Color
alias ls="ls -G"
# Long form no user group, color
alias l="ls -oG"
# List all except . and ..., color, mark file types
alias lsa="ls -AGF"
# List all except . and ..., color, mark file types, long form no user group, file size
alias ll="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Aliases for logo-ls (filetype-appropriate logos)
alias lls='logo-ls'
alias lla='logo-ls -A'
alias lll='logo-ls -al'
# equivalents with Git Status on by Default
alias llsg='logo-ls -D'
alias llag='logo-ls -AD'
alias lllg='logo-ls -alD'

# Fuzzy-find files recursively with a preview
alias rbrowse="fd --hidden --exclude 'node_modules' --exclude '.git' |
               fzf --preview='bat --style=numbers --color=always --line-range :500 {}'"


##
## Git & GitHub
##

alias g="git"

# Define git aliases in gitconfig, just add short versions
# here. E.g. `git c` (for commit) is aliased to `gc`
for gitalias in $(git config --get-regexp ^alias\. | sed -e 's/^alias\.\([^ ]*\) .*$/\1/'); do
  alias "g$gitalias"="git $gitalias"
done

# Alias hub to git
eval "$(hub alias -s)"


##
## Network
##

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done


##
## Ruby & Rails
##

alias be="bundle exec"
alias beg="bundle exec guard"
alias ber="bundle exec rails"
alias bers="bundle exec rspec"

##
## Node.js, NPM & Yarn
##

alias yw="yarn workspace"
alias ywi="yarn workspaces info"


##
## Code Editor
##

alias ci="code-insiders ."


##
## Misc. Applications
##

# Docker
alias dockerclean='docker system prune -f & docker volume prune -f'
