#!/usr/bin/env zsh

# Open this file to edit anytime
alias _alias="$EDITOR $0:A" # $0:A is ref to current script in ZSH

##
## General
##

# Go to ./dotfiles
alias dotfiles="cd $DOTFILES_DIR"

# Allow aliases to be with sudo
alias sudo="sudo "

# Easily refresh the shell by sourcing .zsh
alias refresh="source ~/.zshrc"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# ZSH / Oh My ZSH
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"


##
## File System
##

# Color
alias ls="ls -G"
# Long form no user group, color
alias l="ls -oG"
# List all except . and ..., color, mark file types
alias lsa="ls -AGF"
# List all except . and ..., color, mark file types, long form no user group, file size
alias ll="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"


##
## Git & GitHub
##

# Git commands
alias g="git"
alias gst="git status"
alias gc="git commit --verbose"
alias gco="git checkout"
alias ga="git add"
alias gr="git reset"
alias gl="git l"
alias gd="git diff"

# Alias hub to git
eval "$(hub alias -s)"


##
## Network
##

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done


##
## Ruby & Rails
##

alias be="bundle exec"


##
## Node.js, NPM & Yarn
##

alias yw="yarn workspace"
alias ywi="yarn workspaces info"


##
## Code Editor
##

alias ci="code-insiders ."


##
## Misc. Applications
##

# Docker
alias dockerclean='docker system prune -f & docker volume prune -f'
