#!/usr/bin/env zsh

##
# ZSH Environment Settings
#
# Export environment variables for the current shell session
#

export DOTFILES_DIR="$HOME/.dotfiles" # Used internally

##
# LOCAL
#
source $HOME/.env # Bring in local environment variables

##
# EDITOR
#
export EDITOR='nvim'
export VISUAL='code'

##
# LANGUAGE
#
export LANG="en_US.UTF-8"; # Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8";

##
# TERMINAL
#
export TERM=screen-256color # Use 256 colors

##
# CUSTOM BIN
#
if [[ ! "$PATH" == *"$DOTFILES_DIR/bin"* ]]; then
  # Add .dotfiles/bin scripts to path
  export PATH=$DOTFILES_DIR/bin:$PATH
fi
