##
## ENV SETTINGS
##
source ~/.env

##
## Path Management
##

# Add .dotfiles/bin scripts to path
if [[ ! "$PATH" == *"$DOTFILES_DIR/bin"* ]]; then
  export PATH=$DOTFILES_DIR/bin:$PATH
fi


##
## LANGUAGE ENV SETUP
##

# Ruby / rbenv
# eval "$(rbenv init -)" - not needed b/c provided by ohmyzsh rbenv plugin

# Node / nvm
# Handled by ohmyzsh zsh-nvm plugin
# These configurations help with load time
# # Thanks to https://blog.mattclemente.com/2020/06/26/oh-my-zsh-slow-to-load.html
export NVM_LAZY_LOAD=true
export NVM_COMPLETION=false

# Go: add GOPATH to path (requires go)
if type go &>/dev/null && [[ ! "$PATH" == *$(go env GOPATH)/bin* ]]; then
  export PATH=$PATH:$(go env GOPATH)/bin
fi

function env_rust() {
  source "$HOME/.cargo/env"
}
