##
## ENV SETTINGS
##
source ~/.env


##
## GENERAL ZSH CONFIG
## Must come before other settings
##
source "$DOTFILES_DIR/configs/zsh_config"

##
## OS-SPECIFIC CONFIGS
##
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # For Pop!_OS / Ubuntu
  source "$DOTFILES_DIR/configs/zsh_linux_config"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # For macOS
fi


##
## OH-MY-ZSH CONFIG
##
source "$DOTFILES_DIR/configs/zsh_ohmyzsh_config"


##
## CUSTOM ZSH ALIASES
##
source "$DOTFILES_DIR/configs/zsh_aliases"


##
## LANGUAGE / ENV SETUP SCRIPTS
##

# Ruby / rbenv
eval "$(rbenv init -)"

# FZF: command line fuzzy finder https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
