##
## ENV SETTINGS
##
source ~/.env


##
## GENERAL ZSH CONFIG
## Must come before other settings
##
source "$DOTFILES_DIR/configs/zsh_config"


##
## OH-MY-ZSH CONFIG
##
source "$DOTFILES_DIR/configs/zsh_ohmyzsh_config"


##
## CUSTOM ZSH ALIASES
##
source "$DOTFILES_DIR/configs/zsh_aliases"

